version: "3.8"

services:
  sorfi-db:
    image: 'postgres:16.2-alpine'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: sorfi
    ports:
      - "5431:5432"
    volumes:
      - ./data:/var/lib/postgresql/data