version: '3.8'

services:
  app:
    container_name: PastelariaContainer
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - ./service:/var/www/html
    ports:
      - "8080:8000"
    networks:
      - pasteleria_network

  # Database Service
  db:
    image: 'postgres:16.2-alpine'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
    - "${DB_PORT}:5432"
    networks:
      - pasteleria_network

networks:
  pasteleria_network:
    driver: bridge
